### ISSUE TITLE
Result isn't real shortest way

### ISSUE THREAD

**Issue by emjy86** [RT-Projects/RT.Dijkstra#1]
Hi,

I have tested the sample with ways between cities.
In this sample, we have 1176 miles between Houston and Phoenix and 372 miles between Los Angeles and Phoenix.
If we add a way (imaginary) of 500 miles by example between Houston and Los Angeles, the shortest way should be Houston > Los Angeles > Phoenix (372 + 500 = 872 miles) but the "DijkstrasAlgorithm.Run" method always returns that Houston > Phoenix (1176 miles) is the shortest way, that is wrong...

Sorry for my english.

Thanks.

**Comment by Timwi** [comment]
Thank you for your report! I found the problem and fixed the bug.

**Comment by emjy86** [comment]
Thank you.
